version: '3.8'
services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
  local-server:
    container_name: local-server
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.mastermind.infrastructure.FastAPI.main:app --host 0.0.0.0 --port 8888 --reload"
    ports:
      - "8888:8888"
    volumes:
      - .:/code
    depends_on:
      - db
