"""added guessing model

Revision ID: 09d53592f1d4
Revises: b9d52ca581dd
Create Date: 2022-05-21 09:51:42.221043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d53592f1d4'
down_revision = 'b9d52ca581dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guessings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guessings_id'), 'guessings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guessings_id'), table_name='guessings')
    op.drop_table('guessings')
    # ### end Alembic commands ###
