"""added again attempts

Revision ID: 2269db4d570e
Revises: 2487e2b66cd7
Create Date: 2022-05-21 21:23:12.674540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2269db4d570e'
down_revision = '2487e2b66cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('attempts', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'attempts')
    # ### end Alembic commands ###
