"""added status to Game

Revision ID: 255573f671db
Revises: 3f1b6747e219
Create Date: 2022-05-21 23:20:46.542477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '255573f671db'
down_revision = '3f1b6747e219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    game_status = postgresql.ENUM('PLAYING', 'WON', 'LOST', name='game_status')
    game_status.create(op.get_bind())
    op.add_column('games', sa.Column('status', sa.Enum('PLAYING', 'WON', 'LOST', name='game_status'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'status')
    # ### end Alembic commands ###
