"""changed game id to str

Revision ID: 2efe9e27698c
Revises: 2269db4d570e
Create Date: 2022-05-21 23:02:24.649366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2efe9e27698c'
down_revision = '2269db4d570e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
