"""added again Game class with id type str

Revision ID: 3f1b6747e219
Revises: 17059890b0f1
Create Date: 2022-05-21 23:19:48.149190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f1b6747e219'
down_revision = '17059890b0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('attempts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('feedbacks', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.drop_index('ix_todelete_id', table_name='todelete')
    op.drop_table('todelete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todelete',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='todelete_pkey')
    )
    op.create_index('ix_todelete_id', 'todelete', ['id'], unique=False)
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
