"""solving attempts bug

Revision ID: 4c14320e2c3f
Revises: 7c792540a118
Create Date: 2022-05-21 21:18:11.308725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c14320e2c3f'
down_revision = '7c792540a118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
