"""deleted guessing, improved game

Revision ID: 62c6d15fb12d
Revises: 3561f9621622
Create Date: 2022-05-21 19:23:30.805828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62c6d15fb12d'
down_revision = '3561f9621622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    game_status = postgresql.ENUM('PLAYING', 'WON', 'LOST', name='game_status')
    game_status.create(op.get_bind())
    op.drop_index('ix_guessings_id', table_name='guessings')
    op.drop_table('guessings')
    op.add_column('games', sa.Column('status', sa.Enum('PLAYING', 'WON', 'LOST', name='game_status'), nullable=True))
    op.add_column('games', sa.Column('feedbacks', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'feedbacks')
    op.drop_column('games', 'status')
    op.create_table('guessings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['games.id'], name='guessings_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='guessings_pkey')
    )
    op.create_index('ix_guessings_id', 'guessings', ['id'], unique=False)
    # ### end Alembic commands ###
