"""deleted arrays from game

Revision ID: 67ac0e183f4f
Revises: d68a02c51e7b
Create Date: 2022-05-22 10:17:53.485090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67ac0e183f4f'
down_revision = 'd68a02c51e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'feedbacks')
    op.drop_column('games', 'attempts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('attempts', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('feedbacks', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
