"""deleted guessing, improved game

Revision ID: 7c792540a118
Revises: 62c6d15fb12d
Create Date: 2022-05-21 20:01:11.439984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c792540a118'
down_revision = '62c6d15fb12d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
