"""added game model fixes

Revision ID: 8dc86254a8f9
Revises: e47c5fc8d11c
Create Date: 2022-05-21 10:00:15.719857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc86254a8f9'
down_revision = 'e47c5fc8d11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
