"""added multidimensional arrays to game

Revision ID: 9d09109f14be
Revises: 67ac0e183f4f
Create Date: 2022-05-22 10:18:50.608445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d09109f14be'
down_revision = '67ac0e183f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('attempts', sa.ARRAY(sa.String(), dimensions=2), nullable=True))
    op.add_column('games', sa.Column('feedbacks', sa.ARRAY(sa.String(), dimensions=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'feedbacks')
    op.drop_column('games', 'attempts')
    # ### end Alembic commands ###
