"""added game model fixes

Revision ID: bd49d0a91d66
Revises: 8dc86254a8f9
Create Date: 2022-05-21 10:19:13.907785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd49d0a91d66'
down_revision = '8dc86254a8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_guessings_id', table_name='guessings')
    op.drop_table('guessings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guessings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['games.id'], name='guessings_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='guessings_pkey')
    )
    op.create_index('ix_guessings_id', 'guessings', ['id'], unique=False)
    # ### end Alembic commands ###
