"""changed array dimensions

Revision ID: d68a02c51e7b
Revises: 255573f671db
Create Date: 2022-05-22 10:15:52.980271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68a02c51e7b'
down_revision = '255573f671db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
