"""added guessing model corrections

Revision ID: e47c5fc8d11c
Revises: 09d53592f1d4
Create Date: 2022-05-21 09:55:10.211697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47c5fc8d11c'
down_revision = '09d53592f1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
