"""add feedback as string

Revision ID: f2dcf6f61c56
Revises: e290f920efc3
Create Date: 2022-05-22 12:02:08.258912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2dcf6f61c56'
down_revision = 'e290f920efc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('feedbacks', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'feedbacks')
    # ### end Alembic commands ###
